travis:
  secure:
    BINSTAR_TOKEN: EyWhnQxl0c0+U2comVhWoWXE1BVCeUyO7ch9XUoqHlktFVY9yDBRuxgmcVDBJvTmBiqvp644Cw+GV9wOwfTfj3koYtTvtQ/WKy5xHhPXXnRDkoDTLzXrkLvo0Wt1QvzEWqyawNbRREdV6ldKEWBx9oN6xkrStmXf2LjuXBvdc2NRDzsd8LIGvj4UCkBsPbwHwwG0mrDeCsqv/eaSb7ZA2EDJgOctbjoZQysYaNXp5S99C3Q5Rrr/Qv5jI32QbKlJ8HFZnW5Ye8ve2d2fCkyGq9Ss/POzQtyKcPwwz1hVcI7aaMx+nPddNlQXQPwDff5ifQdY6NGmKHaRuzmUZeNAgVBTVXbuQpKttHUkXn8/Epvfwyh8Cu7nSCH3azjxH8YN5cT2YiW7+Bkf4nIzh/094neORSndPPXgioToHwRv9/f+qA0U1v2M9i6vIOqhQKsCVCmVrG/d47B5IADZNjzZvP5ekVq6kIUcAo+Bebaj3dEXIogW8TEy3RO9JucU+DXNsAXUIyL2kuaNR87zv3j06YycDPAd7phZGyAXtloX3Mp8NI7lwqyExsbdoauB79DJM3GgJ11/I8xd0QoKmTA6VU0ONTuFDZAX9xOLPY47qt3O9+UbpQMcvo1vv6rsMstijOvzYnmmjzCvErz22YEw2/o04MS5NuH8i2cHdVjHy6o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
